name: Validate PR

on:
  push:
    branches:
    - mvvm
  pull_request:
    branches:
    - mvvm

jobs:
  build:
    name: Build-Project
    runs-on: windows-latest
    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: setup-nuget
      uses: NuGet/setup-nuget@v1
    - name: build-solution
      run: |
        msbuild TFAmvvm.sln
          -p:Configuration=Debug
          -p:AppxBundle=Always
          -p:UapAppxPackageBuildMode=CI
          -p:AppxPackageSigningEnabled=false
          -p:PackageCertificateThumbprint=""
          -p:PackageCertificateKeyFile=""